with source as (select * from {{ source("raw_sap", "vbrk") }} where mandt = '100')
select
    vbeln as billing_document,
    fkart as billing_type,
    fktyp as billing_category,
    vbtyp as document_category,
    waerk as document_currency,
    vkorg as sales_organization,
    vtweg as distribution_channel,
    spart as division,
    fkdat as billing_date,
    erdat as created_date,
    ernam as created_by,
    bukrs as company_code,
    netwr as net_value,
    mwsbk as tax_amount,
    kunrg as payer,
    kunag as sold_to_party,
    inco1 as incoterms_1,
    inco2 as incoterms_2,
    zterm as payment_terms,
    gjahr as fiscal_year,
    belnr as accounting_document,
    xblnr as reference_document,
    fksto as cancelled_flag,
    land1 as country_key,
    kurrf as exchange_rate,
    aedat as last_changed_date
from source
