with source as (select * from {{ source("raw_sap", "kna1") }} where mandt = 100)
select
    kunnr as customer_number ,
    land1 as country_key,
    name1 as customer_name,
    name2 as customer_name_2,
    ort01 as city,
    pstlz as postal_code,
    regio as region,
    sortl as sort_field,
    stras as street,
    telf1 as telephone,
    telfx as fax,
    adrnr as address_number,
    anred as title,
    brsch as industry_key,
    erdat as created_date,
    ernam as created_by,
    ktokd as account_group,
    spras as language_key,
    stcd1 as tax_number_1,
    stcd2 as tax_number_2,
    stceg as vat_registration_no,
    lzone as transport_zone,
    kukla as customer_classification,
    lifnr as vendor_number,
    loevm as deletion_flag,
    sperr as central_posting_block,
    konzs as group_key
from source
