with source as (select * from {{ source("raw_sap", "bseg") }} where mandt = 100)
select
    bukrs as company_code,
    belnr as accounting_document,
    gjahr as fiscal_year,
    buzei as line_item,
    bschl as posting_key,
    shkzg as debit_credit_indicator,
    gsber as business_area,
    hkont as gl_account,
    dmbtr as amount_local_currency,
    wrbtr as amount_document_currency,
    mwskz as tax_code,
    kostl as cost_center,
    prctr as profit_center,
    aufnr as order_number,
    kunnr as customer_number,
    lifnr as vendor_number,
    vbeln as sales_document,
    ebeln as purchase_order,
    matnr as material_number,
    werks as plant,
    menge as quantity,
    meins as unit_of_measure,
    sgtxt as item_text,
    zterm as payment_terms,
    zlsch as payment_method,
    zbd1t as discount_days_1,
    zbd2t as discount_days_2,
    zbd3t as net_payment_days,
    zbd1p as discount_percent_1,
    valut as value_date,
    zfbdt as baseline_payment_date,
    augdt as clearing_date,
    augbl as clearing_document,
    segment as segment,
    xblnr as reference_key
from source
